services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress_container
    ports:
      - "80:80"  # Kontainer WordPress berjalan di port 80, diteruskan ke 8080
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - wordpress_data:/var/www/html

  db:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "8080:80"  # Nginx mendengarkan di port 80
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf  # Pastikan file nginx.conf ada
    depends_on:
      - wordpress

volumes:
  wordpress_data:
  db_data: